### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by Faker4564** [Faker4564/protospace-37686#2]
https://protospace-37686.herokuapp.com/

**Comment by shodai-ito** [comment]
@Faker4564 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- [ ] **ログアウト状態のユーザーは、プロトタイプ新規投稿ページ・プロトタイプ編集ページに遷移しようとすると、ログインページにリダイレクトされること**
ログアウト中に編集ページへ遷移しようとすると、ログイン画面でなくトップページへ遷移してしまいます。

【チェック方法】
最初にログアウト状態を作る。投稿ページ・編集ページのURLを打ち込み、ログインページにリダイレクトされれば正常な挙動。

修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by Faker4564** [comment]
修正しました。

**Comment by Faker4564** [comment]
Slackにて[botapp]より、「発展カリキュラム終了、おめでとうございます！」との文章がきましたが、まだLGTMをいただいておりません。この場合はどうすればよろしいでしょうか？

**Comment by snkw-works** [comment]
@Faker4564 さん、大変お待たせいたしました。お問い合わせいただきありがとうございます。

この度は、こちらの不手際によりご迷惑をおかけしてしまい大変申し訳ございませんでした。
挙動確認結果のご連絡ができておりませんでした。

正常に動作することが確認できておりますので、protospaceは「**LGTM**」とさせていただきます。

この後は、[botapp]から届いている最終課題の案内をご確認の上、「**最終課題カリキュラム**」を進めていただきますよう、お願いいたします。

ご不明点がございましたら、お気兼ねなくご連絡ください。
引き続き、スタッフ一同 @Faker4564 さんの学習をサポートさせていただきますので、よろしくお願い申し上げます。
